export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const CREATE_PRODUCTS = 'CREATE_PRODUCTS';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
